# Build all images and run all containers
# `docker-compose -f docker-compose-local.yml up -d --build --force-recreate`

version: '3.7'

services:

  etd-integration-tests:
    container_name: 'etd-integration-tests'
    build:
      context: './'
      dockerfile: './DockerfileLocal'
    volumes:
      - './:/home/etdadm'
      - '/tmp/etd_dash_data/in:/home/etdadm/data/in'
      - 'message.json:/home/etdadmin/message.json'
    env_file:
      - '.env'
    ports:
      # Integration tests
      - '10610:8081'
    networks:
      - etd-net

# Create a custom docker network if it does not exist already
networks:
  etd-net:
    name: etd-net
